const furnitureData = [
    {
      id: 1,
      name: "Modern Sofa",
      price: 299.99,
      category: "Sofas",
      material: "Leather",
      stock: 10,
      dimensions: "200cm x 85cm x 90cm",
      color: "Black",
      thumbnail: "https://images.pexels.com/photos/6492397/pexels-photo-6492397.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      description: "A sleek and stylish leather sofa that adds a modern touch to any living room."
    },
    {
      id: 2,
      name: "Wooden Dining Table",
      price: 499.99,
      category: "Dining Tables",
      material: "Oak Wood",
      stock: 5,
      dimensions: "180cm x 90cm x 75cm",
      color: "Natural",
      thumbnail: "https://images.pexels.com/photos/2829030/pexels-photo-2829030.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      description: "A sturdy oak dining table perfect for family meals and gatherings."
    },
    {
      id: 3,
      name: "Office Chair",
      price: 129.99,
      category: "Chairs",
      material: "Mesh",
      stock: 20,
      dimensions: "120cm x 60cm x 60cm",
      color: "Gray",
      thumbnail: "https://images.pexels.com/photos/1957478/pexels-photo-1957478.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      description: "Ergonomic mesh office chair designed for comfort during long work hours."
    },
    {
      id: 4,
      name: "Queen Bed Frame",
      price: 399.99,
      category: "Beds",
      material: "Metal",
      stock: 7,
      dimensions: "220cm x 160cm x 110cm",
      color: "White",
      thumbnail: "https://images.pexels.com/photos/879010/pexels-photo-879010.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      description: "A stylish white metal queen bed frame that complements any bedroom décor."
    },
    {
      id: 5,
      name: "Glass Coffee Table",
      price: 159.99,
      category: "Coffee Tables",
      material: "Tempered Glass",
      stock: 15,
      dimensions: "100cm x 50cm x 45cm",
      color: "Clear",
      thumbnail: "https://images.pexels.com/photos/932095/pexels-photo-932095.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      description: "Elegant glass coffee table with tempered glass top for a contemporary look."
    },
    {
      id: 6,
      name: "Leather Armchair",
      price: 249.99,
      category: "Chairs",
      material: "Leather",
      stock: 8,
      dimensions: "90cm x 85cm x 100cm",
      color: "Brown",
      thumbnail: "https://images.pexels.com/photos/17514601/pexels-photo-17514601/free-photo-of-leather-armchair-in-a-living-room.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "A cozy brown leather armchair that adds comfort and style to any room."
    },
    {
      id: 7,
      name: "Bookshelf",
      price: 199.99,
      category: "Shelves",
      material: "Wood",
      stock: 12,
      dimensions: "180cm x 80cm x 30cm",
      color: "Walnut",
      thumbnail: "https://images.pexels.com/photos/265004/pexels-photo-265004.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      description: "Spacious wooden bookshelf with a walnut finish, perfect for organizing books and decor."
    },
    {
      id: 8,
      name: "Recliner Sofa",
      price: 599.99,
      category: "Sofas",
      material: "Fabric",
      stock: 6,
      dimensions: "220cm x 100cm x 95cm",
      color: "Gray",
      thumbnail: "https://images.pexels.com/photos/3757055/pexels-photo-3757055.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      description: "Comfortable recliner sofa with soft fabric, perfect for relaxation."
    },
    {
      id: 9,
      name: "Kitchen Bar Stool",
      price: 89.99,
      category: "Chairs",
      material: "Metal & Wood",
      stock: 25,
      dimensions: "110cm x 40cm x 40cm",
      color: "Black & Oak",
      thumbnail: "https://images.pexels.com/photos/8580721/pexels-photo-8580721.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      description: "Stylish kitchen bar stool with a black metal frame and oak wood seat."
    },
    {
      id: 10,
      name: "Wardrobe Closet",
      price: 799.99,
      category: "Wardrobes",
      material: "Pine Wood",
      stock: 4,
      dimensions: "250cm x 180cm x 60cm",
      color: "White",
      thumbnail: "https://images.pexels.com/photos/90319/pexels-photo-90319.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      description: "Spacious pine wood wardrobe closet in white, ideal for storing clothing and accessories."
    },
    {
      id: 11,
      name: "Folding Dining Chair",
      price: 49.99,
      category: "Chairs",
      material: "Plastic & Steel",
      stock: 30,
      dimensions: "80cm x 45cm x 75cm",
      color: "Black",
      thumbnail: "https://images.pexels.com/photos/7587287/pexels-photo-7587287.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      description: "Lightweight folding dining chair, easy to store and perfect for extra seating."
    },
    {
      id: 12,
      name: "Rustic Coffee Table",
      price: 229.99,
      category: "Coffee Tables",
      material: "Reclaimed Wood",
      stock: 10,
      dimensions: "120cm x 70cm x 45cm",
      color: "Dark Brown",
      thumbnail: "https://images.pexels.com/photos/8834717/pexels-photo-8834717.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      description: "Rustic coffee table crafted from reclaimed wood with a dark brown finish."
    },
    {
      id: 13,
      name: "Accent Chair",
      price: 179.99,
      category: "Chairs",
      material: "Fabric",
      stock: 15,
      dimensions: "80cm x 75cm x 90cm",
      color: "Blue",
      thumbnail: "https://images.pexels.com/photos/2766975/pexels-photo-2766975.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      description: "Comfortable blue fabric accent chair perfect for adding a pop of color to any room."
    },
    {
      id: 14,
      name: "Nesting Tables",
      price: 139.99,
      category: "Tables",
      material: "Wood",
      stock: 12,
      dimensions: "Various Sizes",
      color: "Natural",
      thumbnail: "https://images.pexels.com/photos/8967772/pexels-photo-8967772.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      description: "Set of natural wood nesting tables, versatile and space-saving."
    },
    {
      id: 15,
      name: "Storage Ottoman",
      price: 89.99,
      category: "Ottomans",
      material: "Fabric",
      stock: 20,
      dimensions: "60cm x 60cm x 45cm",
      color: "Gray",
      thumbnail: "https://images.pexels.com/photos/7535017/pexels-photo-7535017.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      description: "Functional gray fabric storage ottoman, great for living rooms and bedrooms."
    }
]

export default furnitureData;
